import type { RouteKey } from '@/lib/i18n/routes';

/**
 * Registr editovatelných textů webu.
 *
 * Jediný zdroj pravdy o výchozím znění. Databáze drží jen skutečné odchylky
 * (viz `src/lib/db/content.ts`), takže web běží i s prázdnou tabulkou a změna
 * textu v repozitáři se na webu projeví — pokud ho majitel zrovna nepřepsal.
 *
 * Hodnoty `cs`/`en`/`de` jsou doslovně přepsané z `src/content/copy/*.ts`.
 * Ty soubory zůstávají zdrojem pravdy pro veřejné stránky; tenhle registr je
 * jejich rozpad do bloků, které se dají editovat po jednom. Když se text
 * v `copy/*` změní, musí se změnit i tady, jinak bude administrace nabízet
 * „výchozí znění“, které na webu není.
 *
 * Co sem NEPATŘÍ: popisky ovládacích prvků (stepper, výběr časovky),
 * `aria-label`, validační hlášky formulářů a jednoslovné stavy („Vybráno“,
 * „Plno“). To je chování rozhraní, ne redakční text — kdyby to majitel
 * přepsal, rozbil by ovládání, ne obsah. Bloky ze `src/lib/i18n/dict.ts`
 * sem nepatří vůbec.
 *
 * 🔴 Do bloků jde **prostý text, ne HTML**. Nic z toho se nikdy nesmí
 * vykreslit přes `dangerouslySetInnerHTML` — obsah zapisuje člověk
 * z administrace a jediné, co ho dělí od skriptu na veřejné stránce,
 * je právě to, že ho React vykreslí jako text.
 *
 * Konvence klíčů: `key` je jméno bloku v rámci stránky (bez prefixu). Klíč
 * v databázi vzniká složením `"<stránka>:<blok>"` – viz `src/lib/db/content.ts`.
 */

export type ContentBlockDef = {
  /** Jméno bloku v rámci stránky, např. `hero_nadpis`. Malá písmena, číslice, `_`, `-`, `.`. */
  key: string;
  /** Popisek pole v administraci. */
  label: string;
  /** Volitelné seskupení polí v editoru (sekce stránky). */
  group?: string;
  /** true ⇒ v administraci se vykreslí textarea místo jednořádkového inputu. */
  multiline?: boolean;
  cs: string;
  en: string;
  de: string;
};

/**
 * Stránka webu tak, jak jí říká majitel, a kam na webu vede.
 * `route` je klíč do `ROUTES` — odtud se skládá jak veřejný odkaz, tak cesty,
 * které se po uložení textů musí přegenerovat.
 */
export type ContentPageInfo = { title: string; route: RouteKey };

export const CONTENT_PAGE_INFO: Record<string, ContentPageInfo> = {
  "domu": { title: "Titulní strana", route: "home" },
  "dynovy-svet": { title: "Dýňový svět", route: "pumpkinWorld" },
  "vstupenky": { title: "Vstupenky", route: "tickets" },
  "skoly": { title: "Školy a skupiny dětí", route: "schools" },
  "statek": { title: "Pronájem statku", route: "venue" },
  "blesi-trh": { title: "Dětský bleší trh", route: "fleaMarket" },
  "kontakt": { title: "Kontakt a cesta k nám", route: "contact" },
};

/** Klíč = jméno stránky, hodnota = její bloky v pořadí, v jakém stojí na stránce. */
export const CONTENT_PAGES: Record<string, ContentBlockDef[]> = {
  "domu": [
    {
      key: "kicker",
      label: "Řádek nad hlavním nadpisem (kraj a obec)",
      group: "Úvodní část",
      cs: "Nová Ves u Leštiny · Vysočina",
      en: "Nová Ves u Leštiny · Bohemian-Moravian Highlands",
      de: "Nová Ves u Leštiny · Böhmisch-Mährische Höhe",
    },
    {
      key: "titleTop",
      label: "Hlavní nadpis — první řádek",
      group: "Úvodní část",
      cs: "Dýňový",
      en: "Pumpkin",
      de: "Kürbis",
    },
    {
      key: "titleBottom",
      label: "Hlavní nadpis — druhý řádek (oranžový)",
      group: "Úvodní část",
      cs: "svět",
      en: "World",
      de: "welt",
    },
    {
      key: "lead",
      label: "Úvodní odstavec pod nadpisem",
      group: "Úvodní část",
      multiline: true,
      cs: "Pěstujeme dýně. Na podzim otevřeme dvůr, stodolu i zahradu a ukážeme vám, kolik jich vlastně existuje. Děti mezitím obsadí slámohrad.",
      en: "We grow pumpkins. Every autumn we open the courtyard, the barn and the garden, and show you how many kinds there really are. The children take the straw castle.",
      de: "Wir bauen Kürbisse an. Im Herbst öffnen wir Hof, Scheune und Garten und zeigen Ihnen, wie viele Sorten es wirklich gibt. Die Kinder erobern derweil die Strohburg.",
    },
    {
      key: "watchSeason",
      label: "Tlačítko v úvodu, když prodej ještě neběží (za text se doplní ročník)",
      group: "Úvodní část",
      cs: "Hlídat start sezóny",
      en: "Get told when the season opens",
      de: "Über den Saisonstart informieren",
    },
    {
      key: "whatYouSee",
      label: "Odkaz v úvodu na stránku Dýňový svět",
      group: "Úvodní část",
      cs: "Co u nás uvidíte",
      en: "What there is to see",
      de: "Was es zu sehen gibt",
    },
    {
      key: "statSeason",
      label: "První údaj — popisek („Sezóna“)",
      group: "Tři údaje pod úvodem",
      cs: "Sezóna",
      en: "Season",
      de: "Saison",
    },
    {
      key: "statSeasonNote",
      label: "První údaj — slovo před ročníkem",
      group: "Tři údaje pod úvodem",
      cs: "Ročník",
      en: "Edition",
      de: "Jahrgang",
    },
    {
      key: "statOpen",
      label: "Druhý údaj — popisek („Otevřeno“)",
      group: "Tři údaje pod úvodem",
      cs: "Otevřeno",
      en: "Open",
      de: "Geöffnet",
    },
    {
      key: "statOpenValue",
      label: "Druhý údaj — otevírací doba ve všední dny",
      group: "Tři údaje pod úvodem",
      cs: "st–pá 14—18",
      en: "Wed–Fri 2—6 pm",
      de: "Mi–Fr 14—18 Uhr",
    },
    {
      key: "statOpenNote",
      label: "Druhý údaj — otevírací doba o víkendu a svátcích",
      group: "Tři údaje pod úvodem",
      cs: "so–ne a svátky 10—18",
      en: "Sat–Sun and holidays 10 am — 6 pm",
      de: "Sa–So und Feiertage 10—18 Uhr",
    },
    {
      key: "statPrice",
      label: "Třetí údaj — popisek („Vstupné“)",
      group: "Tři údaje pod úvodem",
      cs: "Vstupné",
      en: "Admission",
      de: "Eintritt",
    },
    {
      key: "statPriceValue",
      label: "Třetí údaj — ceny vstupného",
      group: "Tři údaje pod úvodem",
      cs: "120 / 100 Kč",
      en: "120 / 100 CZK",
      de: "120 / 100 CZK",
    },
    {
      key: "statPriceNote",
      label: "Třetí údaj — poznámka o dětech a psovi",
      group: "Tři údaje pod úvodem",
      cs: "děti do 2 let zdarma · pes 10 Kč",
      en: "under 2s free · dogs 10 CZK",
      de: "Kinder unter 2 frei · Hund 10 CZK",
    },
    {
      key: "doTitle",
      label: "Nadpis oddílu o tom, co se na statku dá dělat",
      group: "Co se dá dělat",
      cs: "Co se na statku dá dělat",
      en: "What there is to do on the farm",
      de: "Was man auf dem Hof machen kann",
    },
    {
      key: "doLead",
      label: "Odstavec pod tímto nadpisem",
      group: "Co se dá dělat",
      multiline: true,
      cs: "Nic z toho není atrakce postavená pro návštěvníky. Je to fungující statek, jen jsme na dva měsíce otevřeli vrata.",
      en: "None of it was built as an attraction. It is a working farm — we just open the gate for two months.",
      de: "Nichts davon wurde für Besucher gebaut. Es ist ein arbeitender Bauernhof — wir öffnen nur für zwei Monate das Tor.",
    },
    {
      key: "photosLabel",
      label: "Popisek nad pásem fotek",
      group: "Pás fotek",
      cs: "Ze statku",
      en: "From the farm",
      de: "Vom Hof",
    },
    {
      key: "varietiesTitle",
      label: "Nadpis oddílu o odrůdách dýní",
      group: "Odrůdy",
      cs: "Odrůdy, které tu letos rostou",
      en: "The varieties growing here this year",
      de: "Die Sorten, die hier dieses Jahr wachsen",
    },
    {
      key: "varietiesLead",
      label: "Odstavec pod tímto nadpisem",
      group: "Odrůdy",
      multiline: true,
      cs: "Semena vozíme od švýcarského a německého dodavatele. Vlastní osivo nenabízíme — dýně se navzájem spráší a příští rok by z nich vyrostlo něco jiného.",
      en: "We buy our seed from a Swiss and a German supplier. We do not sell our own — pumpkins cross-pollinate, and next year you would get something else entirely.",
      de: "Unser Saatgut beziehen wir von einem Schweizer und einem deutschen Lieferanten. Eigenes Saatgut verkaufen wir nicht — Kürbisse kreuzen sich, und im nächsten Jahr wüchse etwas ganz anderes.",
    },
    {
      key: "weight",
      label: "Popisek u váhy dýně",
      group: "Odrůdy",
      cs: "Váha",
      en: "Weight",
      de: "Gewicht",
    },
    {
      key: "goodFor",
      label: "Popisek u využití dýně",
      group: "Odrůdy",
      cs: "Vhodná na",
      en: "Good for",
      de: "Geeignet für",
    },
    {
      key: "animalsTitle",
      label: "Nadpis oddílu o zvířatech",
      group: "Zvířata",
      cs: "Kdo tu bydlí",
      en: "Who lives here",
      de: "Wer hier wohnt",
    },
    {
      key: "animalsLead",
      label: "Odstavec pod tímto nadpisem",
      group: "Zvířata",
      multiline: true,
      cs: "Hospodářská zvířata typická pro český venkov. Většina se dá pohladit, kozičky si berou granule přímo z ruky.",
      en: "The farm animals you would find in any Czech village. Most of them can be stroked; the dwarf goats take pellets straight from your hand.",
      de: "Nutztiere, wie sie zu jedem tschechischen Dorf gehören. Die meisten darf man streicheln, die Zwergziegen fressen die Pellets aus der Hand.",
    },
    {
      key: "beforeTitle",
      label: "Nadpis oddílu s informacemi před cestou",
      group: "Praktické informace",
      cs: "Než vyrazíte",
      en: "Before you set off",
      de: "Bevor Sie losfahren",
    },
    {
      key: "ctaOpen",
      label: "Nadpis výzvy, když je prodej otevřený",
      group: "Závěrečná výzva",
      cs: "Vyberte si den a hodinu",
      en: "Pick your day and hour",
      de: "Wählen Sie Tag und Uhrzeit",
    },
    {
      key: "ctaClosedPrefix",
      label: "Nadpis výzvy, když je prodej zavřený — část před ročníkem",
      group: "Závěrečná výzva",
      cs: "Sezóna",
      en: "The",
      de: "Die Saison",
    },
    {
      key: "ctaClosedSuffix",
      label: "Nadpis výzvy, když je prodej zavřený — část za ročníkem",
      group: "Závěrečná výzva",
      cs: "začíná 20. září",
      en: "season opens on 20 September",
      de: "beginnt am 20. September",
    },
    {
      key: "ctaOpenLead",
      label: "Text pod výzvou, když je prodej otevřený",
      group: "Závěrečná výzva",
      multiline: true,
      cs: "Vstup je na konkrétní čas, aby se na statku nesešlo víc lidí, než unese. Vstupenku dostanete e-mailem jako QR kód.",
      en: "Entry is for a set time, so that the farm never holds more people than it comfortably can. Your ticket arrives by email as a QR code.",
      de: "Der Eintritt gilt für eine feste Uhrzeit, damit nie mehr Menschen auf dem Hof sind, als er verträgt. Das Ticket kommt als QR-Code per E-Mail.",
    },
    {
      key: "ctaClosedLead",
      label: "Text pod výzvou, když je prodej zavřený",
      group: "Závěrečná výzva",
      multiline: true,
      cs: "Nechte nám e-mail a dáme vám vědět v den, kdy se otevře prodej vstupenek. Nic jiného vám posílat nebudeme.",
      en: "Leave us your email and we will write on the day ticket sales open. We will not send you anything else.",
      de: "Hinterlassen Sie uns Ihre E-Mail — wir schreiben an dem Tag, an dem der Ticketverkauf startet. Sonst schicken wir Ihnen nichts.",
    },
    {
      key: "ctaButtonOpen",
      label: "Tlačítko výzvy, když je prodej otevřený",
      group: "Závěrečná výzva",
      cs: "Na vstupenky",
      en: "Go to tickets",
      de: "Zu den Tickets",
    },
    {
      key: "ctaButtonClosed",
      label: "Tlačítko výzvy, když je prodej zavřený",
      group: "Závěrečná výzva",
      cs: "Chci vědět o startu",
      en: "Let me know",
      de: "Benachrichtigt mich",
    },
    {
      key: "orCall",
      label: "Věta před telefonním číslem",
      group: "Závěrečná výzva",
      cs: "Nebo zavolejte",
      en: "Or give us a call",
      de: "Oder rufen Sie an",
    },
  ],

  "dynovy-svet": [
    {
      key: "kicker",
      label: "Řádek nad hlavním nadpisem (termín sezóny)",
      group: "Úvodní část",
      cs: "20. září — 2. listopadu",
      en: "20 September — 2 November",
      de: "20. September — 2. November",
    },
    {
      key: "title",
      label: "Hlavní nadpis stránky",
      group: "Úvodní část",
      cs: "Dýňový svět",
      en: "Pumpkin World",
      de: "Kürbiswelt",
    },
    {
      key: "lead",
      label: "Úvodní odstavec pod nadpisem",
      group: "Úvodní část",
      multiline: true,
      cs: "Na podzim otevřeme dvůr, stodolu i zahradu. Ve stodole stojí regály plné odrůd, které tu za rok vyrostly — u každé je popiska, na co se hodí. Venku slámohrad, slámobazén a děti, které se odmítají vrátit do auta.",
      en: "In autumn we open the courtyard, the barn and the garden. The barn holds shelves of every variety that grew here this year, each with a label saying what it is good for. Outside: the straw castle, the straw pool, and children who refuse to get back in the car.",
      de: "Im Herbst öffnen wir Hof, Scheune und Garten. In der Scheune stehen Regale voller Sorten, die hier dieses Jahr gewachsen sind — bei jeder steht, wofür sie sich eignet. Draußen: Strohburg, Strohbad und Kinder, die nicht mehr ins Auto zurückwollen.",
    },
    {
      key: "pickDate",
      label: "Tlačítko na výběr termínu",
      group: "Úvodní část",
      cs: "Vybrat termín",
      en: "Pick a date",
      de: "Termin wählen",
    },
    {
      key: "schoolLink",
      label: "Odkaz v úvodu pro školy a školky",
      group: "Úvodní část",
      cs: "Jedete se školkou nebo školou?",
      en: "Coming with a nursery or a school?",
      de: "Kommen Sie mit Kindergarten oder Schule?",
    },
    {
      key: "hoursTitle",
      label: "Nadpis nad otevírací dobou",
      group: "Otevírací doba a vstupné",
      cs: "Otevírací doba",
      en: "Opening hours",
      de: "Öffnungszeiten",
    },
    {
      key: "hoursClosed",
      label: "Věta o zavřených dnech pod tabulkou hodin",
      group: "Otevírací doba a vstupné",
      cs: "V pondělí a v úterý je zavřeno.",
      en: "Closed on Mondays and Tuesdays.",
      de: "Montags und dienstags geschlossen.",
    },
    {
      key: "priceTitle",
      label: "Nadpis nad vstupným",
      group: "Otevírací doba a vstupné",
      cs: "Vstupné",
      en: "Admission",
      de: "Eintritt",
    },
    {
      key: "cardNote",
      label: "Poznámka o placení kartou",
      group: "Otevírací doba a vstupné",
      multiline: true,
      cs: "Na statku nejde platit kartou. Hotově nebo QR platbou z telefonu ano — online koupené vstupenky se platí kartou.",
      en: "We cannot take cards on the farm. Cash and QR bank payment from your phone are fine — tickets bought online are paid by card.",
      de: "Auf dem Hof ist keine Kartenzahlung möglich. Bar oder per QR-Überweisung vom Handy geht — online gekaufte Tickets werden mit Karte bezahlt.",
    },
    {
      key: "whatTitle",
      label: "Nadpis oddílu o tom, co na návštěvníky čeká",
      group: "Co se dá dělat",
      cs: "Co tu na vás čeká",
      en: "What is waiting for you",
      de: "Was Sie erwartet",
    },
    {
      key: "whatLead",
      label: "Odstavec pod tímto nadpisem",
      group: "Co se dá dělat",
      multiline: true,
      cs: "Statek funguje celý rok. Na dva měsíce k němu jen přibude výstava a otevřou se vrata.",
      en: "The farm works all year round. For two months an exhibition is added and the gate swings open.",
      de: "Der Hof arbeitet das ganze Jahr. Für zwei Monate kommt eine Ausstellung dazu und das Tor geht auf.",
    },
    {
      key: "varietiesTitle",
      label: "Nadpis oddílu o odrůdách ve stodole",
      group: "Odrůdy",
      cs: "Odrůdy vystavené ve stodole",
      en: "The varieties on show in the barn",
      de: "Die Sorten in der Scheune",
    },
    {
      key: "varietiesLead",
      label: "Odstavec pod tímto nadpisem",
      group: "Odrůdy",
      multiline: true,
      cs: "U každé je popiska s názvem a s tím, na co se hodí. Většinu si můžete rovnou koupit s sebou.",
      en: "Each has a label with its name and what it is good for. Most of them you can buy and take home.",
      de: "Bei jeder steht der Name und wofür sie sich eignet. Die meisten können Sie gleich mitnehmen.",
    },
    {
      key: "animalsTitle",
      label: "Nadpis oddílu o zvířatech",
      group: "Zvířata",
      cs: "Zvířata",
      en: "The animals",
      de: "Die Tiere",
    },
    {
      key: "animalsLead",
      label: "Odstavec pod tímto nadpisem",
      group: "Zvířata",
      multiline: true,
      cs: "Hospodářská zvířata typická pro český venkov. Kozičky si berou granule přímo z ruky.",
      en: "The farm animals you would find in any Czech village. The dwarf goats take pellets straight from your hand.",
      de: "Nutztiere, wie sie zu jedem tschechischen Dorf gehören. Die Zwergziegen fressen die Pellets aus der Hand.",
    },
    {
      key: "beforeTitle",
      label: "Nadpis oddílu s informacemi před cestou",
      group: "Praktické informace",
      cs: "Než vyrazíte",
      en: "Before you set off",
      de: "Bevor Sie losfahren",
    },
    {
      key: "ctaTitle",
      label: "Nadpis závěrečné výzvy",
      group: "Závěrečná výzva",
      cs: "Vstup je na konkrétní hodinu",
      en: "Entry is for a set hour",
      de: "Der Eintritt gilt für eine feste Uhrzeit",
    },
    {
      key: "ctaLead",
      label: "Text pod závěrečnou výzvou",
      group: "Závěrečná výzva",
      multiline: true,
      cs: "Držíme tím počet lidí na statku tak, aby si všichni měli kde hrát. Uvnitř pak můžete zůstat, jak dlouho chcete.",
      en: "That way the farm never gets so full that there is nowhere to play. Once inside, you can stay as long as you like.",
      de: "So wird der Hof nie so voll, dass zum Spielen kein Platz bleibt. Drinnen können Sie bleiben, solange Sie möchten.",
    },
    {
      key: "preferPhone",
      label: "Věta nabízející domluvu po telefonu",
      group: "Závěrečná výzva",
      cs: "Raději po telefonu?",
      en: "Rather do it by phone?",
      de: "Lieber telefonisch?",
    },
  ],

  "vstupenky": [
    {
      key: "titlePrefix",
      label: "Hlavní nadpis stránky (za něj se doplní ročník)",
      group: "Úvodní část",
      cs: "Vstupenky do Dýňového světa",
      en: "Tickets for Pumpkin World",
      de: "Eintrittskarten für die Kürbiswelt",
    },
    {
      key: "lead",
      label: "Úvodní odstavec pod nadpisem",
      group: "Úvodní část",
      multiline: true,
      cs: "Vstup na konkrétní hodinu. Držíme tím počet lidí na statku tak, aby si všichni měli kde hrát a bylo na koho se dívat.",
      en: "Entry is for a set hour. That keeps the number of people on the farm at a level where everyone has room to play and something to look at.",
      de: "Der Eintritt gilt für eine feste Uhrzeit. So bleibt die Zahl der Gäste auf dem Hof so, dass alle Platz zum Spielen haben.",
    },
    {
      key: "notOpenYet",
      label: "Hláška, když prodej na novou sezónu ještě neběží (zápis {season} se nahradí ročníkem — nechte ho v textu)",
      group: "Úvodní část",
      multiline: true,
      cs: "Prodej vstupenek na sezónu {season} zatím neběží. Termíny níže jsou vypsané, ale nakupovat půjde až od začátku září — dáme vědět e-mailem i na Facebooku.",
      en: "Ticket sales for the {season} season have not opened yet. The dates below are published, but buying starts in early September — we will announce it by email and on Facebook.",
      de: "Der Ticketverkauf für die Saison {season} läuft noch nicht. Die Termine unten stehen fest, gekauft wird ab Anfang September — wir melden uns per E-Mail und auf Facebook.",
    },
    {
      key: "noDates",
      label: "Text, když nejsou vypsané žádné termíny",
      group: "Výběr termínu",
      multiline: true,
      cs: "Termíny pro nadcházející sezónu ještě nejsou vypsané. Nechte nám e-mail a dáme vám vědět, jakmile se prodej otevře.",
      en: "The dates for the coming season are not published yet. Leave us your email and we will let you know as soon as sales open.",
      de: "Die Termine für die kommende Saison stehen noch nicht fest. Hinterlassen Sie uns Ihre E-Mail — wir melden uns, sobald der Verkauf startet.",
    },
    {
      key: "slotsLead",
      label: "Věta nad výběrem dne a hodiny",
      group: "Výběr termínu",
      multiline: true,
      cs: "Vstup je na konkrétní hodinu, ať se na statku nesejde víc lidí, než unese. Uvnitř pak můžete zůstat, jak dlouho chcete.",
      en: "Entry is for a set hour so the farm never holds more people than it can. Once inside, stay as long as you like.",
      de: "Der Eintritt gilt für eine feste Uhrzeit, damit der Hof nie überfüllt ist. Drinnen bleiben Sie, solange Sie möchten.",
    },
    {
      key: "basketTitle",
      label: "Nadpis nad seznamem vybraných vstupenek",
      group: "Vybrané vstupenky",
      cs: "Vstupenky",
      en: "Your tickets",
      de: "Ihre Karten",
    },
    {
      key: "continueToPayment",
      label: "Tlačítko k platbě",
      group: "Vybrané vstupenky",
      cs: "Pokračovat k platbě",
      en: "Continue to payment",
      de: "Weiter zur Zahlung",
    },
    {
      key: "paymentNote",
      label: "Text pod tlačítkem k platbě",
      group: "Vybrané vstupenky",
      multiline: true,
      cs: "Platí se kartou online. Vstupenku dostanete e-mailem jako QR kód — stačí ho u vstupu ukázat v telefonu. Místo vám držíme 15 minut.",
      en: "Payment is by card online. Your ticket arrives by email as a QR code — just show it on your phone at the gate. We hold your place for 15 minutes.",
      de: "Bezahlt wird online per Karte. Das Ticket kommt als QR-Code per E-Mail — am Eingang einfach auf dem Handy zeigen. Wir halten Ihren Platz 15 Minuten.",
    },
    {
      key: "faq1Title",
      label: "První otázka — nadpis",
      group: "Časté otázky",
      cs: "Proč na čas",
      en: "Why timed entry",
      de: "Warum feste Zeiten",
    },
    {
      key: "faq1Text",
      label: "První otázka — odpověď",
      group: "Časté otázky",
      cs: "Statek má svoji kapacitu. Když se v jednu chvíli sejde příliš lidí, nikdo si nic neužije.",
      en: "The farm has a capacity. If too many people arrive at once, nobody enjoys it.",
      de: "Der Hof hat eine Kapazität. Kommen zu viele Menschen auf einmal, hat niemand etwas davon.",
    },
    {
      key: "faq2Title",
      label: "Druhá otázka — nadpis",
      group: "Časté otázky",
      cs: "Jak vstupenka vypadá",
      en: "What the ticket looks like",
      de: "Wie das Ticket aussieht",
    },
    {
      key: "faq2Text",
      label: "Druhá otázka — odpověď",
      group: "Časté otázky",
      multiline: true,
      cs: "Přijde e-mailem jako QR kód. U vstupu ho ukážete v telefonu, tisknout nemusíte.",
      en: "It arrives by email as a QR code. Show it on your phone at the gate — no need to print it.",
      de: "Es kommt als QR-Code per E-Mail. Am Eingang zeigen Sie es auf dem Handy, ausdrucken müssen Sie nichts.",
    },
    {
      key: "faq3Title",
      label: "Třetí otázka — nadpis",
      group: "Časté otázky",
      cs: "Když nemůžete přijet",
      en: "If you cannot make it",
      de: "Wenn Sie nicht kommen können",
    },
    {
      key: "faq3Text",
      label: "Třetí otázka — odpověď",
      group: "Časté otázky",
      cs: "Ozvěte se nám na telefon nebo e-mail a domluvíme se na jiném termínu.",
      en: "Call us or drop us an email and we will find another date together.",
      de: "Rufen Sie an oder schreiben Sie uns — wir finden einen anderen Termin.",
    },
    {
      key: "faq4Title",
      label: "Čtvrtá otázka — nadpis",
      group: "Časté otázky",
      cs: "Platba na místě",
      en: "Paying on site",
      de: "Zahlung vor Ort",
    },
    {
      key: "faq4Text",
      label: "Čtvrtá otázka — odpověď",
      group: "Časté otázky",
      cs: "Kartou na statku bohužel ne. Hotově nebo QR platbou z telefonu ano.",
      en: "We cannot take cards on the farm. Cash or a QR bank payment from your phone is fine.",
      de: "Kartenzahlung ist auf dem Hof leider nicht möglich. Bar oder per QR-Überweisung geht.",
    },
    {
      key: "callUs",
      label: "Věta před telefonním číslem",
      group: "Závěrečná výzva",
      cs: "Nejde to, nebo si nejste jistí? Zavolejte na",
      en: "Stuck, or not sure? Give us a ring on",
      de: "Klappt es nicht oder sind Sie unsicher? Rufen Sie an unter",
    },
  ],

  "skoly": [
    {
      key: "kicker",
      label: "Řádek nad hlavním nadpisem",
      group: "Úvodní část",
      cs: "Dopolední programy",
      en: "Morning programmes",
      de: "Vormittagsprogramme",
    },
    {
      key: "title",
      label: "Hlavní nadpis stránky",
      group: "Úvodní část",
      cs: "Pro školky, první stupeň a skupiny dětí",
      en: "For nurseries, primary schools and children's groups",
      de: "Für Kindergärten, Grundschulen und Kindergruppen",
    },
    {
      key: "lead",
      label: "Úvodní odstavec pod nadpisem",
      group: "Úvodní část",
      multiline: true,
      cs: "Dva programy podle ročního období. Na podzim výstava dýní a zahrada se slámou, na jaře les upravený pro volnou hru. Obojí venku, obojí končí tak, aby se stihl oběd.",
      en: "Two programmes, one for each season. In autumn the pumpkin exhibition and a garden full of straw; in spring a forest laid out for free play. Both outdoors, both finish in time for lunch.",
      de: "Zwei Programme, je nach Jahreszeit. Im Herbst die Kürbisausstellung und ein Garten voller Stroh, im Frühjahr ein Wald zum freien Spielen. Beides draußen, beides endet rechtzeitig vor dem Mittagessen.",
    },
    {
      key: "programLabel",
      label: "Slovo nad číslem programu",
      group: "Úvodní část",
      cs: "Program",
      en: "Programme",
      de: "Programm",
    },
    {
      key: "howTitle",
      label: "Nadpis oddílu o průběhu návštěvy",
      group: "Jak návštěva probíhá",
      cs: "Jak to u nás chodí",
      en: "How a visit works",
      de: "Wie ein Besuch abläuft",
    },
    {
      key: "howLead",
      label: "Odstavec pod tímto nadpisem",
      group: "Jak návštěva probíhá",
      cs: "Většinu otázek dostáváme opakovaně, tak je tu rovnou zodpovídáme.",
      en: "We get the same questions again and again, so here are the answers.",
      de: "Dieselben Fragen kommen immer wieder — hier sind die Antworten.",
    },
    {
      key: "weatherTitle",
      label: "Nadpis oddílu o počasí",
      group: "Když se pokazí počasí",
      cs: "Když se pokazí počasí",
      en: "If the weather turns",
      de: "Wenn das Wetter umschlägt",
    },
    {
      key: "weather1",
      label: "První odstavec o počasí — zrušení výletu",
      group: "Když se pokazí počasí",
      multiline: true,
      cs: "Výlet se dá bez dalšího odvolat. Vždycky si bereme telefon na organizátora a jednou až dvakrát za sezónu školky sami obvoláváme — když má pršet celý den, výlet by nebyl příjemný. Vaše rozhodnutí výlet zrušit respektujeme stejně.",
      en: "The trip can be called off with no further ado. We always take the organiser's phone number and once or twice a season we ring round ourselves — a whole day of rain makes for a miserable outing. If you decide to cancel, we respect that just the same.",
      de: "Der Ausflug kann jederzeit abgesagt werden. Wir notieren uns immer die Telefonnummer der Organisatoren und rufen ein- bis zweimal pro Saison selbst an — bei Dauerregen macht der Besuch keine Freude. Sagen Sie ab, ist das für uns ebenso in Ordnung.",
    },
    {
      key: "weather2",
      label: "Druhý odstavec o počasí — kam se schovat",
      group: "Když se pokazí počasí",
      multiline: true,
      cs: "Když nepřeje jen část dopoledne, máme dost krytého prostoru: stodolu, patro ve stodole, zastřešený prostor u stodoly, restauraci a venkovní posezení. Na podzim se dá tou dobou zabavit vyřezáváním dýně.",
      en: "If only part of the morning is wet, we have plenty of cover: the barn, the loft above it, the roofed area beside it, the restaurant and the outdoor seating. In autumn that is a good moment for pumpkin carving.",
      de: "Regnet es nur zeitweise, gibt es genug überdachten Platz: die Scheune, das Obergeschoss, den überdachten Bereich daneben, das Restaurant und den Sitzbereich draußen. Im Herbst bietet sich dann das Kürbisschnitzen an.",
    },
    {
      key: "testimonialsTitle",
      label: "Nadpis nad ohlasy škol",
      group: "Reference škol",
      cs: "Co nám napsaly školy",
      en: "What the schools wrote to us",
      de: "Was uns die Schulen geschrieben haben",
    },
    {
      key: "formTitle",
      label: "Nadpis formuláře",
      group: "Formulář",
      cs: "Domluvit termín",
      en: "Arrange a date",
      de: "Termin vereinbaren",
    },
    {
      key: "formLeadPrefix",
      label: "Text nad formulářem (končí telefonním číslem)",
      group: "Formulář",
      multiline: true,
      cs: "Napište nám, o jaký program máte zájem a kolik dětí přijede. Ozveme se e-mailem nebo telefonicky. Rychlejší je zavolat na",
      en: "Tell us which programme you are interested in and how many children are coming. We will reply by email or phone. Calling is faster:",
      de: "Schreiben Sie uns, welches Programm Sie interessiert und wie viele Kinder kommen. Wir antworten per E-Mail oder Telefon. Schneller geht es telefonisch:",
    },
    {
      key: "formDateLabel",
      label: "Popisek pole s termínem",
      group: "Formulář",
      cs: "Předběžný termín",
      en: "Provisional date",
      de: "Wunschtermin",
    },
    {
      key: "formDateHint",
      label: "Vysvětlivka pod polem s termínem",
      group: "Formulář",
      cs: "Nemusí být závazný, upřesníme spolu.",
      en: "Not binding — we can nail it down together.",
      de: "Nicht verbindlich — wir legen ihn gemeinsam fest.",
    },
    {
      key: "formRadioLegend",
      label: "Otázka nad výběrem programu",
      group: "Formulář",
      cs: "O jaký program jde",
      en: "Which programme",
      de: "Um welches Programm geht es",
    },
    {
      key: "formOption1",
      label: "První volba programu",
      group: "Formulář",
      cs: "Výlet do Dýňového světa",
      en: "A trip to Pumpkin World",
      de: "Ausflug in die Kürbiswelt",
    },
    {
      key: "formOption2",
      label: "Druhá volba programu",
      group: "Formulář",
      cs: "Výlet do lesa – Příroda hrou",
      en: "A trip to the forest – Nature at Play",
      de: "Waldausflug – Natur zum Spielen",
    },
    {
      key: "formOption3",
      label: "Třetí volba programu",
      group: "Formulář",
      cs: "Ještě nevím",
      en: "Not sure yet",
      de: "Weiß ich noch nicht",
    },
    {
      key: "formMessageLabel",
      label: "Popisek pole se zprávou",
      group: "Formulář",
      cs: "Poznámka",
      en: "Note",
      de: "Anmerkung",
    },
    {
      key: "formMessageHint",
      label: "Vysvětlivka pod polem se zprávou",
      group: "Formulář",
      cs: "Počet dětí, věk, jestli chcete malé dýně pro každého.",
      en: "Number of children, their age, whether you want a small pumpkin for each of them.",
      de: "Anzahl der Kinder, Alter, ob Sie für jedes einen kleinen Kürbis möchten.",
    },
    {
      key: "operatorNote",
      label: "Věta o provozovatelích (zápisy ve složených závorkách se nahradí jménem a IČ — nechte je v textu)",
      group: "Patička stránky",
      multiline: true,
      cs: "Lesní programy provozuje {spolek}, IČO {icoSpolek}. Dýňový svět provozuje {owner}, IČ {ico}.",
      en: "The forest programmes are run by {spolek}, ID No. {icoSpolek}. Pumpkin World is run by {owner}, ID No. {ico}.",
      de: "Die Waldprogramme betreibt {spolek}, IdNr. {icoSpolek}. Die Kürbiswelt betreibt {owner}, IdNr. {ico}.",
    },
  ],

  "statek": [
    {
      key: "kicker",
      label: "Řádek nad hlavním nadpisem",
      group: "Úvodní část",
      cs: "Svatby · oslavy · firemní akce",
      en: "Weddings · celebrations · company days",
      de: "Hochzeiten · Feiern · Firmenfeste",
    },
    {
      key: "title",
      label: "Hlavní nadpis stránky",
      group: "Úvodní část",
      cs: "Statek si můžete pronajmout",
      en: "You can hire the whole farm",
      de: "Sie können den Hof mieten",
    },
    {
      key: "lead",
      label: "Úvodní odstavec pod nadpisem",
      group: "Úvodní část",
      multiline: true,
      cs: "Nabízíme prostory Statku u Pipků k pořádání svateb, oslav a podobných soukromých či firemních akcí. Můžete využít vybavenou restauraci, uzavřený dvůr, stodolu i zahradu.",
      en: "The spaces of Statek u Pipků are available for weddings, celebrations and similar private or company events. You can use the fitted restaurant, the enclosed courtyard, the barn and the garden.",
      de: "Die Räume des Statek u Pipků stehen für Hochzeiten, Feiern und ähnliche private oder betriebliche Veranstaltungen zur Verfügung. Nutzbar sind das eingerichtete Restaurant, der geschlossene Hof, die Scheune und der Garten.",
    },
    {
      key: "spacesTitle",
      label: "Nadpis nad výčtem prostor",
      group: "Co je k dispozici",
      cs: "Co je k dispozici",
      en: "What is available",
      de: "Was zur Verfügung steht",
    },
    {
      key: "formTitle",
      label: "Nadpis formuláře",
      group: "Formulář",
      cs: "Poptávka pořádání akce",
      en: "Event enquiry",
      de: "Anfrage für eine Veranstaltung",
    },
    {
      key: "formLead",
      label: "Text nad formulářem",
      group: "Formulář",
      multiline: true,
      cs: "Napište nám, o jakou akci jde a jaký bude předběžný počet účastníků. Ozveme se co nejdřív zpátky.",
      en: "Tell us what kind of event it is and roughly how many people are coming. We will get back to you as soon as we can.",
      de: "Schreiben Sie uns, um welche Veranstaltung es geht und mit wie vielen Gästen Sie rechnen. Wir melden uns so schnell wie möglich.",
    },
    {
      key: "formDateLabel",
      label: "Popisek pole s termínem akce",
      group: "Formulář",
      cs: "Předběžný termín akce",
      en: "Provisional date of the event",
      de: "Voraussichtlicher Termin",
    },
    {
      key: "formRadioLegend",
      label: "Otázka nad výběrem, o co má zájemce zájem",
      group: "Formulář",
      cs: "Mám zájem o",
      en: "I am interested in",
      de: "Ich interessiere mich für",
    },
    {
      key: "formOption1",
      label: "První volba",
      group: "Formulář",
      cs: "Konzultaci",
      en: "A conversation",
      de: "Ein Beratungsgespräch",
    },
    {
      key: "formOption2",
      label: "Druhá volba",
      group: "Formulář",
      cs: "Cenovou nabídku",
      en: "A quote",
      de: "Ein Angebot",
    },
    {
      key: "formMessageLabel",
      label: "Popisek pole se zprávou",
      group: "Formulář",
      cs: "Zpráva",
      en: "Message",
      de: "Nachricht",
    },
    {
      key: "formMessageHint",
      label: "Vysvětlivka pod polem se zprávou",
      group: "Formulář",
      cs: "O jakou akci se jedná a kolik lidí přibližně přijede.",
      en: "What kind of event it is and roughly how many people will come.",
      de: "Um welche Veranstaltung es geht und wie viele Gäste ungefähr kommen.",
    },
    {
      key: "formSubmit",
      label: "Tlačítko na odeslání formuláře",
      group: "Formulář",
      cs: "Poptat",
      en: "Send enquiry",
      de: "Anfragen",
    },
    {
      key: "orCall",
      label: "Věta před telefonním číslem",
      group: "Formulář",
      cs: "Nebo rovnou zavolejte",
      en: "Or just give us a call",
      de: "Oder rufen Sie einfach an",
    },
  ],

  "blesi-trh": [
    {
      key: "kicker",
      label: "Řádek nad hlavním nadpisem",
      group: "Úvodní část",
      cs: "Bleší trh · SWAP · rodinný víkend",
      en: "Flea market · SWAP · family weekend",
      de: "Flohmarkt · SWAP · Familienwochenende",
    },
    {
      key: "title",
      label: "Hlavní nadpis stránky",
      group: "Úvodní část",
      cs: "Dětský bleší trh",
      en: "Children's flea market",
      de: "Kinderflohmarkt",
    },
    {
      key: "lead",
      label: "Úvodní odstavec pod nadpisem",
      group: "Úvodní část",
      multiline: true,
      cs: "Děti mohou s pomocí rodičů prodávat své hračky, hry, knížky, oblečení i sportovní potřeby, které už nepotřebují. Můžete prodávat, kupovat, nebo se jen přijít podívat.",
      en: "With a hand from their parents, children can sell the toys, games, books, clothes and sports kit they have outgrown. Come to sell, to buy, or just to look.",
      de: "Mit Hilfe der Eltern können Kinder Spielzeug, Spiele, Bücher, Kleidung und Sportsachen verkaufen, die sie nicht mehr brauchen. Sie können verkaufen, kaufen oder einfach vorbeischauen.",
    },
    {
      key: "reuse",
      label: "Odstavec o myšlence druhého života věcí",
      group: "Úvodní část",
      multiline: true,
      cs: "Celá akce stojí na myšlence reuse — věcem dáváme druhý život. Nevyhazujeme, co už nepotřebujeme, ale posouváme dál, aby udělaly radost někomu dalšímu. Děti navíc získávají zkušenost s hodnotou věcí a základy finanční gramotnosti.",
      en: "The whole thing rests on reuse — giving things a second life. Instead of throwing away what we no longer need, we pass it on so it can please someone else. And children get a feel for what things are worth, and a first taste of handling money.",
      de: "Die ganze Veranstaltung baut auf Reuse — wir geben Dingen ein zweites Leben. Was wir nicht mehr brauchen, werfen wir nicht weg, sondern geben es weiter, damit es jemand anderem Freude macht. Nebenbei lernen die Kinder, was Dinge wert sind, und machen erste Erfahrungen mit Geld.",
    },
    {
      key: "nextEdition",
      label: "Odstavec o tom, kdy byl poslední ročník a kdy bude další",
      group: "Úvodní část",
      multiline: true,
      cs: "I. ročník proběhl 28.—29. června 2025. Termín dalšího ročníku zatím není vypsaný — nechte nám e-mail ve formuláři níže a dáme vám vědět.",
      en: "The first edition took place on 28–29 June 2025. The date of the next one is not set yet — leave us your email in the form below and we will tell you.",
      de: "Die erste Auflage fand am 28.–29. Juni 2025 statt. Der Termin für die nächste steht noch nicht fest — hinterlassen Sie unten Ihre E-Mail, wir melden uns.",
    },
    {
      key: "priceTitle",
      label: "Nadpis nad vstupným",
      group: "Vstupné a co je v ceně",
      cs: "Vstupné",
      en: "Admission",
      de: "Eintritt",
    },
    {
      key: "includedTitle",
      label: "Nadpis nad výčtem toho, co je v ceně",
      group: "Vstupné a co je v ceně",
      cs: "Co je v ceně vstupného",
      en: "What admission includes",
      de: "Was im Eintritt enthalten ist",
    },
    {
      key: "refreshments",
      label: "Věta o občerstvení a parkování",
      group: "Vstupné a co je v ceně",
      cs: "Občerstvení otevřeno. Parkování zdarma.",
      en: "Refreshments open. Parking free.",
      de: "Imbiss geöffnet. Parken kostenlos.",
    },
    {
      key: "rulesTitle",
      label: "Nadpis nad pravidly",
      group: "Pravidla pro prodávající",
      cs: "Pravidla pro prodávající",
      en: "Rules for sellers",
      de: "Regeln für Verkäufer",
    },
    {
      key: "rulesLead",
      label: "Odstavec pod tímto nadpisem",
      group: "Pravidla pro prodávající",
      multiline: true,
      cs: "Prodej je určený pro nepodnikající, soukromé prodávající. Stánkaři jen po předchozí domluvě s organizátorem.",
      en: "Selling is for private, non-commercial sellers. Traders only by prior arrangement with the organiser.",
      de: "Der Verkauf ist für private, nicht gewerbliche Verkäufer gedacht. Händler nur nach vorheriger Absprache mit dem Veranstalter.",
    },
    {
      key: "rulesNote",
      label: "Poznámka pod pravidly o vyloučení prodávajícího",
      group: "Pravidla pro prodávající",
      cs: "Organizátor si vyhrazuje právo vyloučit prodávajícího v případě prodeje nevhodného zboží.",
      en: "The organiser reserves the right to exclude a seller offering unsuitable goods.",
      de: "Der Veranstalter behält sich vor, Verkäufer mit ungeeigneter Ware auszuschließen.",
    },
    {
      key: "formTitle",
      label: "Nadpis formuláře",
      group: "Formulář",
      cs: "Chci vědět o dalším ročníku",
      en: "Tell me about the next edition",
      de: "Über die nächste Auflage informieren",
    },
    {
      key: "formLead",
      label: "Text nad formulářem",
      group: "Formulář",
      cs: "Jakmile vypíšeme termín, ozveme se e-mailem. Nic jiného vám posílat nebudeme.",
      en: "As soon as we set a date we will email you. We will not send you anything else.",
      de: "Sobald der Termin feststeht, schreiben wir Ihnen. Sonst schicken wir Ihnen nichts.",
    },
    {
      key: "formRadioLegend",
      label: "Otázka nad výběrem zájmu",
      group: "Formulář",
      cs: "Mám zájem",
      en: "I would like to",
      de: "Ich möchte",
    },
    {
      key: "formOption1",
      label: "První volba — přijít jako návštěvník",
      group: "Formulář",
      cs: "Přijít jako návštěvník",
      en: "Come as a visitor",
      de: "Als Besucher kommen",
    },
    {
      key: "formOption2",
      label: "Druhá volba — přijet prodávat",
      group: "Formulář",
      cs: "Přijet prodávat",
      en: "Come and sell",
      de: "Verkaufen kommen",
    },
    {
      key: "formOption3",
      label: "Třetí volba — jen informovat o akcích",
      group: "Formulář",
      cs: "Jen mě informujte o dalších akcích na statku",
      en: "Just keep me posted about events on the farm",
      de: "Mich nur über weitere Veranstaltungen informieren",
    },
    {
      key: "formMessageLabel",
      label: "Popisek pole se zprávou",
      group: "Formulář",
      cs: "Poznámka nebo dotaz",
      en: "Note or question",
      de: "Anmerkung oder Frage",
    },
    {
      key: "formSubmit",
      label: "Tlačítko na odeslání formuláře",
      group: "Formulář",
      cs: "Odeslat",
      en: "Send",
      de: "Absenden",
    },
  ],

  "kontakt": [
    {
      key: "kicker",
      label: "Řádek nad hlavním nadpisem",
      group: "Úvodní část",
      cs: "Nová Ves u Leštiny · Vysočina",
      en: "Nová Ves u Leštiny · Bohemian-Moravian Highlands",
      de: "Nová Ves u Leštiny · Böhmisch-Mährische Höhe",
    },
    {
      key: "title",
      label: "Hlavní nadpis stránky",
      group: "Úvodní část",
      cs: "Dostanete se k nám autem i vlakem",
      en: "You can reach us by car and by train",
      de: "Sie erreichen uns mit dem Auto und mit der Bahn",
    },
    {
      key: "byTrain",
      label: "Nadpis o cestě vlakem",
      group: "Jak se k nám dostanete",
      cs: "Vlakem",
      en: "By train",
      de: "Mit der Bahn",
    },
    {
      key: "byTrainText",
      label: "Text o cestě vlakem",
      group: "Jak se k nám dostanete",
      multiline: true,
      cs: "Přímo v Nové Vsi u Leštiny je vlaková zastávka. Ujdete pár metrů do kopce a jste u nás na statku.",
      en: "There is a railway stop right in Nová Ves u Leštiny. A few metres uphill and you are at the farm.",
      de: "Direkt in Nová Ves u Leštiny gibt es eine Bahnhaltestelle. Ein paar Meter bergauf und Sie sind auf dem Hof.",
    },
    {
      key: "byCar",
      label: "Nadpis o cestě autem",
      group: "Jak se k nám dostanete",
      cs: "Autem",
      en: "By car",
      de: "Mit dem Auto",
    },
    {
      key: "byCarText",
      label: "Text o cestě autem a parkování",
      group: "Jak se k nám dostanete",
      cs: "Parkování je označené směrovými tabulemi, cca 50 m od statku. Zdarma.",
      en: "Parking is signposted, about 50 m from the farm. Free of charge.",
      de: "Der Parkplatz ist ausgeschildert, etwa 50 m vom Hof entfernt. Kostenlos.",
    },
    {
      key: "coordinates",
      label: "Nadpis nad souřadnicemi",
      group: "Jak se k nám dostanete",
      cs: "Souřadnice",
      en: "Coordinates",
      de: "Koordinaten",
    },
    {
      key: "coordFarm",
      label: "Popisek u souřadnic statku",
      group: "Jak se k nám dostanete",
      cs: "statek",
      en: "farm",
      de: "Hof",
    },
    {
      key: "coordParking",
      label: "Popisek u souřadnic parkoviště",
      group: "Jak se k nám dostanete",
      cs: "parkoviště",
      en: "car park",
      de: "Parkplatz",
    },
    {
      key: "wifi",
      label: "Nadpis o připojení k internetu",
      group: "Jak se k nám dostanete",
      cs: "Wi-Fi",
      en: "Wi-Fi",
      de: "WLAN",
    },
    {
      key: "wifiText",
      label: "Text o připojení k internetu",
      group: "Jak se k nám dostanete",
      cs: "V celém areálu zdarma.",
      en: "Free across the whole site.",
      de: "Auf dem gesamten Gelände kostenlos.",
    },
    {
      key: "mapTitle",
      label: "Popis mapy (čtou ho i hlasové čtečky)",
      group: "Mapa",
      cs: "Mapa — Statek u Pipků, Nová Ves u Leštiny 5",
      en: "Map — Statek u Pipků, Nová Ves u Leštiny 5",
      de: "Karte — Statek u Pipků, Nová Ves u Leštiny 5",
    },
    {
      key: "mapOpen",
      label: "Odkaz na otevření větší mapy",
      group: "Mapa",
      cs: "Otevřít mapu ve větším",
      en: "Open a larger map",
      de: "Größere Karte öffnen",
    },
    {
      key: "formTitle",
      label: "Nadpis formuláře",
      group: "Formulář",
      cs: "Napište nám",
      en: "Write to us",
      de: "Schreiben Sie uns",
    },
    {
      key: "formLead",
      label: "Text nad formulářem",
      group: "Formulář",
      cs: "Na e-maily odpovídáme obvykle do druhého dne. Když spěcháte, zavolejte.",
      en: "We usually answer emails by the next day. If it is urgent, call us.",
      de: "E-Mails beantworten wir meist bis zum nächsten Tag. Wenn es eilt, rufen Sie an.",
    },
    {
      key: "formMessageLabel",
      label: "Popisek pole se zprávou",
      group: "Formulář",
      cs: "Zpráva",
      en: "Message",
      de: "Nachricht",
    },
    {
      key: "formSubmit",
      label: "Tlačítko na odeslání formuláře",
      group: "Formulář",
      cs: "Odeslat",
      en: "Send",
      de: "Absenden",
    },
    {
      key: "billingTitle",
      label: "Nadpis oddílu s fakturačními údaji",
      group: "Fakturační údaje",
      cs: "Fakturační údaje",
      en: "Billing details",
      de: "Rechnungsdaten",
    },
    {
      key: "billingOperator",
      label: "Popisek u provozovatele",
      group: "Fakturační údaje",
      cs: "Provozovatel",
      en: "Operator",
      de: "Betreiber",
    },
    {
      key: "billingSeat",
      label: "Popisek u sídla",
      group: "Fakturační údaje",
      cs: "Sídlo",
      en: "Registered address",
      de: "Sitz",
    },
    {
      key: "billingBank",
      label: "Popisek u bankovního účtu",
      group: "Fakturační údaje",
      cs: "Bankovní účet",
      en: "Bank account",
      de: "Bankverbindung",
    },
    {
      key: "billingForest",
      label: "Popisek u provozovatele lesních programů",
      group: "Fakturační údaje",
      cs: "Lesní programy",
      en: "Forest programmes",
      de: "Waldprogramme",
    },
    {
      key: "idNo",
      label: "Zkratka pro identifikační číslo podnikatele",
      group: "Fakturační údaje",
      cs: "IČ",
      en: "ID No.",
      de: "IdNr.",
    },
    {
      key: "idNoAssoc",
      label: "Zkratka pro identifikační číslo spolku",
      group: "Fakturační údaje",
      cs: "IČO",
      en: "ID No.",
      de: "IdNr.",
    },
  ],
};

/** Jména stránek v pořadí, v jakém se mají nabízet v administraci. */
export const CONTENT_PAGE_KEYS = Object.keys(CONTENT_PAGES);
